#middleware
DOMAIN_DATA = "DOMAIN_DATA"
DOMAIN_LIMIT = 200

#pipeline, spider
URL_DATA = "URL_DATA"
WORD_DATA = "WORD_DATA"
CRAWLER_DATA = "CRAWLER_DATA"
COLLOCATIONS_DATA = "COLLOCATIONS_DATA"
FREQ_DATA = "FREQ_DATA"

#dbname
DB_NAME = "SPIDER_DB"
